name: Node.js CI

on:
  push:
    branches: [ "front-end/dev" ]
  pull_request:
    branches: [ "front-end/dev" ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front/
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './front/package-lock.json'
      - name: Generate Environment Variables File for Production
        run: |
          echo "REACT_APP_S3_ACCESS_KET_ID=${{ secrets.REACT_APP_S3_ACCESS_KET_ID }}" >> .env
          echo "REACT_APP_S3_SECRET_ACCESSKEY=${{ secrets.REACT_APP_S3_SECRET_ACCESSKEY }}" >> .env
          echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
      - name: Install dependencies
        run: npm i
      - name: Build project
        run: npm run build
        env:
          CI: false
                
                
      - name: Deploy to AWS S3
        uses: awact/s3-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './front/build'
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REACT_APP_S3_ACCESS_KET_ID: ${{ secrets.REACT_APP_S3_ACCESS_KET_ID }}
          REACT_APP_S3_SECRET_ACCESSKEY: ${{ secrets.REACT_APP_S3_SECRET_ACCESSKEY }}
